# === BASIC SITE SETTINGS ===
title: "Shilpa Sanapala Portfolio"
title_separator: "-"
name: "Shilpa Sanapala"
description: "Staff scientist combining benchwork with computational bioinformatics."
locale: "en-US"
url: "https://shilpasanapala.github.io"
baseurl: ""
repository: "shilpasanapala/shilpasanapala.github.io"

# === AUTHOR PROFILE (Sidebar Info) ===
author:
  avatar: "profile.png"
  name: "Shilpa Sanapala"
  bio: "Bioinformatics and virology enthusiast"
  location: "Saint Louis, MO"
  employer: "Washington University in St. Louis"
  email: "shilpa.sanapala@wustl.edu"
  orcid: "http://orcid.org/0000-0002-2902-1521"
  pubmed: "https://pubmed.ncbi.nlm.nih.gov/?sort=date&term=Sanapala+S&cauthor_id=27060051"
  researchgate: "https://www.researchgate.net/profile/Shilpa-Sanapala"
  googlescholar: "https://scholar.google.com/citations?user=v77y8dsAAAAJ&hl=en"
  linkedin: "https://www.linkedin.com/in/shilpa-sanapala-87410217/"
  instagram: "shilpasans"
  bluesky: "bsky.app"

# === COLLECTIONS ===
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
  
# === DEFAULT FRONT MATTER SETTINGS ===
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: project
      author_profile: true

# === PLUGINS ===
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-gist

# === OTHER SETTINGS ===
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"

include:
  - .htaccess
  - _pages
  - files
  - _portfolio
  - images

exclude:
  - node_modules
  - vendor
  - tmp
  - Gemfile
  - Gemfile.lock
  - README.md

permalink: /:categories/:title/

